// USER reduser
export const SET_USER = `SET_USER`
export const UPDATE_USER_INFO = `UPDATE_USER_INFO`
export const ADD_PROJECT_ID = `ADD_PROJECT_ID`
export const FOLLOW_TOGGLE = `FOLLOW_TOGGLE`

// USERS reduser
export const UPDATE_USERS = `UPDATE_USERS`

// PROJECTS reduser
export const GET_PROJECTS = `GET_PROJECTS`
export const GET_PROJECTS_SUCCESS = `GET_PROJECTS_SUCCESS`
export const GET_PROJECTS_FAIL = `GET_PROJECTS_FAIL`
export const GET_PROJECT_DETAILS = `GET_PROJECT_DETAILS`
export const GET_PROJECT_DETAILS_SUCCESS = `GET_PROJECT_DETAILS_SUCCESS`
export const GET_PROJECT_DETAILS_FAIL = `GET_PROJECT_DETAILS_FAIL`
export const ADD_PROJECT = `ADD_PROJECT`
export const EDIT_NEED_LIST = `EDIT_NEED_LIST`
export const EDIT_SKILLS_STACK = `EDIT_SKILLS_STACK`
export const EDIT_DESCRIPTION = `EDIT_DESCRIPTION`
export const EDIT_TITLE = `EDIT_TITLE`
export const EDIT_STATUS = `EDIT_STATUS`
export const APPLY_REQUEST = `APPLY_REQUEST`
export const APPROVE_REQUEST = `APPROVE_REQUEST`
export const DECLINE_REQUEST = `DECLINE_REQUEST`

// ROELS reduser
export const GET_ROLES = `GET_ROLES`

// SKILLS reduser
export const GET_SKILLS = `GET_SKILLS`