// USER reduser
export const SET_USER = `SET_USER`

export const GET_CURRENT_USER = `GET_CURRENT_USER`
export const GET_CURRENT_USER_SUCCESS = `GET_CURRENT_USER_SUCCESS`
export const GET_CURRENT_USER_FAIL = `GET_CURRENT_USER_FAIL`

export const UPDATE_USER_INFO = `UPDATE_USER_INFO`
export const UPDATE_USER_INFO_SUCCESS = `UPDATE_USER_INFO_SUCCESS`
export const UPDATE_USER_INFO_FAIL = `UPDATE_USER_INFO_FAIL`

export const ADD_PROJECT_ID = `ADD_PROJECT_ID`

export const FOLLOW_TOGGLE = `FOLLOW_TOGGLE`
export const FOLLOW_TOGGLE_SUCCESS = `FOLLOW_TOGGLE_SUCCESS`
export const FOLLOW_TOGGLE_FAIL = `FOLLOW_TOGGLE_FAIL`

// USERS reduser
export const UPDATE_USERS = `UPDATE_USERS`

export const GET_USER = `GET_USER`
export const GET_USER_SUCCESS = `GET_USER_SUCCESS`
export const GET_USER_FAIL = `GET_USER_FAIL`

export const GET_USERS = `GET_USERS`
export const GET_ALL_USERS = `GET_ALL_USERS`
export const GET_USERS_SUCCESS = `GET_USERS_SUCCESS`
export const GET_USERS_FAIL = `GET_USERS_FAIL`

// PROJECTS reduser
export const GET_PROJECTS = `GET_PROJECTS`
export const GET_ALL_PROJECTS = `GET_ALL_PROJECTS`
export const GET_PROJECTS_SUCCESS = `GET_PROJECTS_SUCCESS`
export const GET_PROJECTS_FAIL = `GET_PROJECTS_FAIL`

export const GET_PROJECT_DETAILS = `GET_PROJECT_DETAILS`
export const GET_PROJECT_DETAILS_SUCCESS = `GET_PROJECT_DETAILS_SUCCESS`
export const GET_PROJECT_DETAILS_FAIL = `GET_PROJECT_DETAILS_FAIL`

export const ADD_PROJECT = `ADD_PROJECT`
export const ADD_PROJECT_SUCCESS = `ADD_PROJECT_SUCCESS`
export const ADD_PROJECT_FAIL = `ADD_PROJECT_FAIL`

export const UPDATE_PROJECT = `UPDATE_PROJECT`
export const UPDATE_PROJECT_SUCCESS = `UPDATE_PROJECT_SUCCESS`
export const UPDATE_PROJECT_FAIL = `UPDATE_PROJECT_FAIL`

export const APPLY_REQUEST = `APPLY_REQUEST`
export const APPROVE_REQUEST = `APPROVE_REQUEST`
export const DECLINE_REQUEST = `DECLINE_REQUEST`
export const REQUEST_SUCCESS = `REQUEST_SUCCESS`
export const REQUEST_FAIL = `REQUEST_FAIL`


// ROELS reduser
export const GET_ROLES = `GET_ROLES`

// SKILLS reduser
export const GET_SKILLS = `GET_SKILLS`