// USER reduser
export const SET_USER = `SET_USER`
export const EDIT_FIRSTNAME = `EDIT_FIRSTNAME`
export const EDIT_LASTNAME = `EDIT_LASTNAME`
export const EDIT_CITY = `EDIT_CITY`
export const EDIT_COUNTRY = `EDIT_COUNTRY`
export const EDIT_BIO = `EDIT_BIO`
export const EDIT_ROLES = `EDIT_ROLES`
export const EDIT_SKILLS = `EDIT_SKILLS`
export const EDIT_SOCIALS_VK = `EDIT_SOCIALS_VK`
export const EDIT_SOCIALS_FACEBOOK = `EDIT_SOCIALS_FACEBOOK`
export const EDIT_SOCIALS_LINKEDIN = `EDIT_SOCIALS_LINKEDIN`
export const EDIT_SOCIALS_GITHUB = `EDIT_SOCIALS_GITHUB`
export const ADD_PROJECT_ID = `ADD_PROJECT_ID`
export const FOLLOW_TOGGLE = `FOLLOW_TOGGLE`

// USERS reduser
export const UPDATE_USERS = `UPDATE_USERS`

// PROJECTS reduser
export const ADD_PROJECT = `ADD_PROJECT`
export const EDIT_NEED_LIST = `EDIT_NEED_LIST`
export const EDIT_SKILLS_STACK = `EDIT_SKILLS_STACK`
export const EDIT_DESCRIPTION = `EDIT_DESCRIPTION`
export const EDIT_TITLE = `EDIT_TITLE`
export const EDIT_STATUS = `EDIT_STATUS`
export const APPLY_REQUEST = `APPLY_REQUEST`
export const APPROVE_REQUEST = `APPROVE_REQUEST`
export const DECLINE_REQUEST = `DECLINE_REQUEST`

// ROELS reduser
export const GET_ROLES = `GET_ROLES`

// SKILLS reduser
export const GET_SKILLS = `GET_SKILLS`